### ISSUE TITLE
Why even use a nested `ListView`?

### ISSUE THREAD

**Issue by tp** [IhorKlimov/Flutter-Nested-ListView#1]
Hey @IhorKlimov,

I read a lot of code lately that was building a grouped listed and used nested `ListView`s like your article at http://myhexaville.com/2018/06/04/flutter-nested-listview/ and the code here (https://github.com/IhorKlimov/Flutter-Nested-ListView/blob/master/lib/example_one.dart#L28) talk about.

I guess not a small amount of people were influenced by your post, because their code looks so eerily similar.

I have been wondering though what drove you and drives others to use the nested `ListView` in the first place. Is the `itemBuilder` really that nice to use? 

The performance benefits one usually gains from using `ListView.builder` as not there for the nested `ListView`s anymore, as I have explored here: https://timm.preetz.name/articles/nested-listviews-in-flutter

Would love to get your opinion on this.

**Comment by IhorKlimov** [comment]
@tp 

Thanks, I didn't know I had such a great influence. Wow

It was a sarcasm

Did you come here to blame me for other people's bad code? I'm not interested in this conversation and I don't like your negative vibe, buddy

**Comment by tp** [comment]
Hey @IhorKlimov,

> Did you come here to blame me for other people's bad code?

No. I just wanted to try to understand why people are looking to get this exact setup working and from there work on showing a more suitable approach.

I think your post (as many out there) was just a train of thought at that point in time, so I would also be interested in your personal opinion on this and whether you think that still thanks today.

> I'm not interested in this conversation

I'm sorry to hear that but then I'll close this ticket.

> I don't like your negative vibe, buddy

Would you mind telling me what part of this caused this reaction? It's not my intention to put anyone off a technical discussion by inappropriate phrasings and I would like to rectify that.

Thanks!
